// Mocks generated by Mockito 5.4.4 from annotations
// in terralinkapp/test/mocks/common/constants_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:terralinkapp/core/common/constants.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [Constants].
///
/// See the documentation for Mockito's code generation for more information.
class MockConstants extends _i1.Mock implements _i2.Constants {
  MockConstants() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getTasksSummaryApiBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getTasksSummaryApiBaseUrl,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getTasksSummaryApiBaseUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String getTasksSbsApiBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getTasksSbsApiBaseUrl,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getTasksSbsApiBaseUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String getNewsApiBaseUrl() => (super.noSuchMethod(
        Invocation.method(
          #getNewsApiBaseUrl,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getNewsApiBaseUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String getWsUrl() => (super.noSuchMethod(
        Invocation.method(
          #getWsUrl,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getWsUrl,
            [],
          ),
        ),
      ) as String);

  @override
  String getGlobalWebPage() => (super.noSuchMethod(
        Invocation.method(
          #getGlobalWebPage,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getGlobalWebPage,
            [],
          ),
        ),
      ) as String);

  @override
  String getRuWebPage() => (super.noSuchMethod(
        Invocation.method(
          #getRuWebPage,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getRuWebPage,
            [],
          ),
        ),
      ) as String);

  @override
  String getMsalTenantId() => (super.noSuchMethod(
        Invocation.method(
          #getMsalTenantId,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getMsalTenantId,
            [],
          ),
        ),
      ) as String);

  @override
  String getMsalClientId() => (super.noSuchMethod(
        Invocation.method(
          #getMsalClientId,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getMsalClientId,
            [],
          ),
        ),
      ) as String);

  @override
  String getMsalScope() => (super.noSuchMethod(
        Invocation.method(
          #getMsalScope,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getMsalScope,
            [],
          ),
        ),
      ) as String);

  @override
  String getMsalRedirectUri() => (super.noSuchMethod(
        Invocation.method(
          #getMsalRedirectUri,
          [],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #getMsalRedirectUri,
            [],
          ),
        ),
      ) as String);
}
