// Mocks generated by Mockito 5.4.4 from annotations
// in terralinkapp/test/mocks/data/providers/dio_provider_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:terralinkapp/core/http/providers/dio_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioProvider extends _i1.Mock implements _i3.DioProvider {
  MockDioProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio provideDio({List<_i2.InterceptorsWrapper>? interceptorList}) =>
      (super.noSuchMethod(
        Invocation.method(
          #provideDio,
          [],
          {#interceptorList: interceptorList},
        ),
        returnValue: _FakeDio_0(
          this,
          Invocation.method(
            #provideDio,
            [],
            {#interceptorList: interceptorList},
          ),
        ),
      ) as _i2.Dio);
}
